### ISSUE TITLE
isZero is not working properly

### ISSUE THREAD

**Issue by koldat** [bwakell/Huldra#4] opened 2016-08-03 08:53 UTC
When you have 0 in BigInt and add(0L) it is resized thus isZero is not working. It should probably be:
    public boolean isZero() {
        for (int i = 0; i < len; i++) {
            if (dig[i] != 0) {
                return false;
            }
        }
        return true;
    }

**Comment by bwakell** [comment] 2016-08-03 10:12
Nicely spotted.
I'd however argue that the issue is in uaddMag(), since the class kind of relies on the invariant that there should be no leading zeroes.

(I'll try to fix this bug and some others once I get time. Maybe this weekend?)

**Comment by bwakell** [comment] 2016-08-06 11:28
OK this should've been fixed now. I also added a test for this.

**Closed by bwakell** 2016-08-06 11:28 UTC
